import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import {
  Cursor,
  CursorProvider,
} from "@/components/animate-ui/components/animate/cursor";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <CursorProvider>
          <Cursor />
          {children}
          <Toaster position="top-center" />
        </CursorProvider>
      </body>
    </html>
  );
}
